# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import movies_pb2 as movies__pb2


class MoviesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMovies = channel.unary_unary(
                '/movies.Movies/GetMovies',
                request_serializer=movies__pb2.GetMoviesRequest.SerializeToString,
                response_deserializer=movies__pb2.GetMoviesResult.FromString,
                )


class MoviesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetMovies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MoviesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMovies': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMovies,
                    request_deserializer=movies__pb2.GetMoviesRequest.FromString,
                    response_serializer=movies__pb2.GetMoviesResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'movies.Movies', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Movies(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMovies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/movies.Movies/GetMovies',
            movies__pb2.GetMoviesRequest.SerializeToString,
            movies__pb2.GetMoviesResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
