# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: users.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0busers.proto\x12\x05users\"/\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\">\n\x0fGetUsersRequest\x12\x0e\n\x06groups\x18\x01 \x03(\t\x12\x0b\n\x03\x61ge\x18\x02 \x03(\t\x12\x0e\n\x06\x63ities\x18\x03 \x03(\t\",\n\x0eGetUsersResult\x12\x1a\n\x05users\x18\x01 \x03(\x0b\x32\x0b.users.User\"$\n\x16GetEmailConfirmRequest\x12\n\n\x02id\x18\x01 \x01(\t\"B\n\x15GetEmailConfirmResult\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x0c\n\x04link\x18\x03 \x01(\t2\x96\x01\n\x05Users\x12;\n\x08GetUsers\x12\x16.users.GetUsersRequest\x1a\x15.users.GetUsersResult\"\x00\x12P\n\x0fGetEmailConfirm\x12\x1d.users.GetEmailConfirmRequest\x1a\x1c.users.GetEmailConfirmResult\"\x00\x62\x06proto3')



_USER = DESCRIPTOR.message_types_by_name['User']
_GETUSERSREQUEST = DESCRIPTOR.message_types_by_name['GetUsersRequest']
_GETUSERSRESULT = DESCRIPTOR.message_types_by_name['GetUsersResult']
_GETEMAILCONFIRMREQUEST = DESCRIPTOR.message_types_by_name['GetEmailConfirmRequest']
_GETEMAILCONFIRMRESULT = DESCRIPTOR.message_types_by_name['GetEmailConfirmResult']
User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
  'DESCRIPTOR' : _USER,
  '__module__' : 'users_pb2'
  # @@protoc_insertion_point(class_scope:users.User)
  })
_sym_db.RegisterMessage(User)

GetUsersRequest = _reflection.GeneratedProtocolMessageType('GetUsersRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETUSERSREQUEST,
  '__module__' : 'users_pb2'
  # @@protoc_insertion_point(class_scope:users.GetUsersRequest)
  })
_sym_db.RegisterMessage(GetUsersRequest)

GetUsersResult = _reflection.GeneratedProtocolMessageType('GetUsersResult', (_message.Message,), {
  'DESCRIPTOR' : _GETUSERSRESULT,
  '__module__' : 'users_pb2'
  # @@protoc_insertion_point(class_scope:users.GetUsersResult)
  })
_sym_db.RegisterMessage(GetUsersResult)

GetEmailConfirmRequest = _reflection.GeneratedProtocolMessageType('GetEmailConfirmRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETEMAILCONFIRMREQUEST,
  '__module__' : 'users_pb2'
  # @@protoc_insertion_point(class_scope:users.GetEmailConfirmRequest)
  })
_sym_db.RegisterMessage(GetEmailConfirmRequest)

GetEmailConfirmResult = _reflection.GeneratedProtocolMessageType('GetEmailConfirmResult', (_message.Message,), {
  'DESCRIPTOR' : _GETEMAILCONFIRMRESULT,
  '__module__' : 'users_pb2'
  # @@protoc_insertion_point(class_scope:users.GetEmailConfirmResult)
  })
_sym_db.RegisterMessage(GetEmailConfirmResult)

_USERS = DESCRIPTOR.services_by_name['Users']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USER._serialized_start=22
  _USER._serialized_end=69
  _GETUSERSREQUEST._serialized_start=71
  _GETUSERSREQUEST._serialized_end=133
  _GETUSERSRESULT._serialized_start=135
  _GETUSERSRESULT._serialized_end=179
  _GETEMAILCONFIRMREQUEST._serialized_start=181
  _GETEMAILCONFIRMREQUEST._serialized_end=217
  _GETEMAILCONFIRMRESULT._serialized_start=219
  _GETEMAILCONFIRMRESULT._serialized_end=285
  _USERS._serialized_start=288
  _USERS._serialized_end=438
# @@protoc_insertion_point(module_scope)
