# Generated by Django 3.2 on 2022-06-30 15:00

from django.db import migrations, models
import django.db.models.deletion
import notices.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='title')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
            ],
            options={
                'verbose_name': 'app',
                'verbose_name_plural': 'apps',
                'db_table': 'notice"."app',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='notices.app', verbose_name='app')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
                'db_table': 'notice"."event',
                'unique_together': {('app', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('method', models.CharField(choices=[('email', 'E-mail'), ('sms', 'SMS'), ('telegram', 'Telegram'), ('websocket', 'Websocket')], default='email', max_length=20, verbose_name='delivery method')),
                ('controlled_by_user', models.BooleanField(default=False, verbose_name='controlled by user')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='notices.event', verbose_name='event')),
            ],
            options={
                'verbose_name': 'notice',
                'verbose_name_plural': 'notices',
                'db_table': 'notice"."notice',
                'unique_together': {('event', 'method')},
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('notice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='notices.notice', verbose_name='notice')),
                ('body', models.TextField(blank=True, help_text='Allowed variables:<br>{{ name }} - user name<br>{{ login }} - user login<br>{{ email }} - user email', validators=[notices.validators.validate_syntax], verbose_name='message body')),
            ],
            options={
                'verbose_name': 'template',
                'verbose_name_plural': 'templates',
                'db_table': 'notice"."template',
            },
        ),
        migrations.CreateModel(
            name='UserNotice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('user_id', models.UUIDField(verbose_name='user id')),
                ('notice', models.ForeignKey(limit_choices_to={'controlled_by_user': True}, on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='notices.notice', verbose_name='notice')),
            ],
            options={
                'verbose_name': 'user notice',
                'verbose_name_plural': 'user notices',
                'db_table': 'notice"."user_notice',
                'unique_together': {('user_id', 'notice')},
            },
        ),
    ]
